kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_user
    password:
      from_secret: docker_password
    repo: habituszin/test
    tags: latest
